### ISSUE TITLE
Importing static data does not work properly

### ISSUE THREAD

**Issue by kilkun** [inkyblackness/hacked#53]
On Fedora using XFCE + Thunar, HackEd does not properly detect when files/folders are dragged into its interface. With no other way to get the editor to recognize static data, it is rendered unusable. 

A nice addition would be the ability to identify paths to data via text input, whether in the GUI, in an external config, or through a flag as a launch parameter.

**Comment by dertseha** [comment]
Hello there and thank you for your message!

yup, without file dragging almost no file/path action will work in the editor :/ I'll take this as the motivation to finally get #2 as well as #16 going.

Meanwhile, do you have alternative systems to work on, or are you now blocked from modding?

**Comment by kilkun** [comment]
Yes, I have a tower running Windows, works fine there!

**Comment by dertseha** [comment]
The `master` branch has been extended to make use of sqweek/dialog - which delegates to file dialogs from the window management system. On *nix systems this would be GTK based. All the drag'n'drop dialogs now also sport a "Browse..." button that spawns the external dialogs.

May I ask you to see if this works in your environment as well? (Or were you downloading the binary?)

Despite the extra dependency, this would be a cheap way to solve it, as I'd rather want to avoid implementing file browsing dialogs ;)

**Comment by dertseha** [comment]
Native dialogs in use now for some time. Closing issue.
