### ISSUE TITLE
Textures not displaying

### ISSUE THREAD

**Issue by ArtInPinkerton** [inkyblackness/hacked#55]
Textures aren't displaying. I can see the labels if I load the main data but all textures are black. Win10 on Nvidia GPU if that matters

<img width="950" alt="Hackedissue" src="https://user-images.githubusercontent.com/67075416/87592189-114c2200-c6af-11ea-8720-6007d1a8f6c8.png">

**Comment by dertseha** [comment]
Hello there and thank you for your message!
That's curious.
How does your project load setup look like? (i.e., which folders are loaded, which files are in there...)

**Comment by ArtInPinkerton** [comment]
I wanted to try and do a texture pack for the main game. I use the Enhanced Edition. I had to unzip the sshock.kpf file and then I navigated to the Res/PC/ folder (which has /CDROM and /HD in it. I dragged /HD onto the the LOAD popup in Hacked and it loads everything as shown. Can see level stuff but the textures are all black. If I hover over them, i see the names of the textures in both texture mode and level tiles.

**Comment by dertseha** [comment]
Ah, OK, thank you.
When you also add the data folder of the CD folder to the "static data", then everything should show up. The resource files are split up into these two locations.
Please try this as well.

**Comment by ArtInPinkerton** [comment]
That worked!!! Thanks for such a speedy response.

**Comment by dertseha** [comment]
Sure thing :) You can read up more detail on the project system [on the Wiki here](https://github.com/inkyblackness/hacked/wiki/Project) (as well as much more information :) )
Have fun - and I'm curious about your project!
