### ISSUE TITLE
Request: Add "light delta" editing to map tiles

### ISSUE THREAD

**Issue by jramstedt** [inkyblackness/hacked#60]
There is currently no way to edit "Light delta" data.
This is needed to set initial values before they are changed by "Change Lighting" trigger.

I'm trying to replicate the death trap's "lights go off" effect in reactor level.
This is how it should be set up:

Base light levels are 0
Initial light delta levels are set to higher (such as 7)

When  "Change Lighting" triggers it sets new delta levels (for example 0)

**Comment by dertseha** [comment]
Thank you for this message!
It's been some time (years!) since I worked on this - though I should be able to make this small extension. :)

**Comment by dertseha** [comment]
Small things are easily possible. Here you go - https://github.com/inkyblackness/hacked/releases/tag/v1.9.0 :D
