### ISSUE TITLE
Bug: 9/1/x and 9/4/x  types should have comparator fail message index in highest byte

### ISSUE THREAD

**Issue by jramstedt** [inkyblackness/hacked#62]
[Here is link to source code where this functionality is used](https://github.com/Interrupt/systemshock/blob/ae36cec2c301a0b28221eb499cf23208be65f316/src/GameSrc/objuse.c#L875C1-L880C22)

I can give more details if needed.

**Comment by dertseha** [comment]
Thank you for reporting. Added with [v1.10.0](https://github.com/inkyblackness/hacked/releases/tag/v1.10.0). Please check - if this is still of interest for you - as I didn't know of a sample case.
