### ISSUE TITLE
Bug: Condition/comparer isn't editable when action is "Nothing"

### ISSUE THREAD

**Issue by jramstedt** [inkyblackness/hacked#64]
[Reference code](https://github.com/Interrupt/systemshock/blob/ae36cec2c301a0b28221eb499cf23208be65f316/src/GameSrc/objuse.c#L211C12-L220C14)

For example in medical the "blocked by shodan" door south east corner has "LockVariableIndex" that actually is index to other trap object from which the condition is used (If you set the nearby null trigger 139 action to something, it will show the security value check condition).

Fix:
Always show condition settings even if action is nothing.

**Comment by dertseha** [comment]
Thank you for reporting. Included in [v1.10.0](https://github.com/inkyblackness/hacked/releases/tag/v1.10.0).
