### ISSUE TITLE
TreasureType Editing Functionality

### ISSUE THREAD

**Issue by XLightningStormL** [inkyblackness/hacked#66]
Basically TreasureTypes are what System Shock 1 uses for randomized Loot Pools for certain corpses and enemies. An example is the Cyborg Assassin loot pool includes stuff like Teflon Rounds, Needles, and rarely Tranqs. 

Currently there isn't any way to actually modify these pools, so I am unable to add say Riot Gun slugs to the Assassin loot pools, or remove EMP Grenades from the Cyber Enforcer's loot pool (these are just examples)

**Comment by dertseha** [comment]
Hi there, thank you for your message!
Unfortunately, the loot tables and their distribution is hardcoded in the engine. They are not sitting in the data files, they are encoded in the source.
For reference, see AI.C from the [original source](https://github.com/NightDive-Studio/shockmac/blob/master/ShockMac/Game%20Src/AI.C) - or, a little easier to read online, from the [Schockolate project](https://github.com/Interrupt/systemshock/blob/master/src/GameSrc/ai.c#L321), `treasure_table`.

In theory, if the engine maintainers would agree on a format, we could implement a parameterized table from a data file, however I guess the chances are slim.
